import { buildOpenApiDocument } from "../../../../shared/openapi/openapi";
import { env } from "../config/env";

export const apiGatewayOpenApiDocument = buildOpenApiDocument({
  title: "FMS API Gateway",
  description: "Reverse-proxy entry point for all backend domain services.",
  version: "1.0.0",
  serverUrl: `http://localhost:${env.port}`,
  tags: [
    { name: "Gateway", description: "Gateway health and monitoring endpoints" },
    { name: "Auth", description: "Proxy endpoints for the auth service" },
    { name: "Users", description: "Proxy endpoints for the user service" },
    { name: "Extinguishers", description: "Proxy endpoints for the extinguisher service" },
    { name: "Inspections", description: "Proxy endpoints for the inspection service" },
    { name: "Maintenance", description: "Proxy endpoints for the maintenance domain" },
    { name: "Reports", description: "Proxy endpoints for the reporting service" },
    { name: "Notifications", description: "Proxy endpoints for the notification service" }
  ],
  endpoints: [
    { method: "get", path: "/api/health", summary: "Gateway health check", tags: ["Gateway"] },
    { method: "get", path: "/api/monitoring", summary: "Gateway monitoring status", tags: ["Gateway"] },
    { method: "get", path: "/metrics", summary: "Prometheus metrics endpoint", tags: ["Gateway"] },
    { method: "get", path: "/api/auth", summary: "Proxy auth service status", tags: ["Auth"] },
    { method: "post", path: "/api/auth/register", summary: "Proxy auth register", tags: ["Auth"] },
    { method: "post", path: "/api/auth/login", summary: "Proxy auth login", tags: ["Auth"] },
    { method: "post", path: "/api/auth/logout", summary: "Proxy auth logout", tags: ["Auth"], secured: true },
    { method: "post", path: "/api/auth/refresh-token", summary: "Proxy auth token refresh", tags: ["Auth"] },
    { method: "post", path: "/api/auth/forgot-password", summary: "Proxy auth forgot password", tags: ["Auth"] },
    { method: "post", path: "/api/auth/reset-password", summary: "Proxy auth reset password", tags: ["Auth"] },
    { method: "get", path: "/api/auth/validate-token", summary: "Proxy auth token validation", tags: ["Auth"], secured: true },
    { method: "get", path: "/api/users/meta", summary: "Proxy user service metadata", tags: ["Users"], secured: true },
    { method: "get", path: "/api/users", summary: "Proxy list users", tags: ["Users"], secured: true },
    { method: "get", path: "/api/users/me", summary: "Proxy current user profile", tags: ["Users"], secured: true },
    { method: "patch", path: "/api/users/me", summary: "Proxy update current user profile", tags: ["Users"], secured: true },
    { method: "patch", path: "/api/users/change-password", summary: "Proxy change password", tags: ["Users"], secured: true },
    { method: "get", path: "/api/users/:id", summary: "Proxy get user by id", tags: ["Users"], secured: true },
    { method: "patch", path: "/api/users/:id", summary: "Proxy update user by id", tags: ["Users"], secured: true },
    { method: "delete", path: "/api/users/:id", summary: "Proxy delete user by id", tags: ["Users"], secured: true },
    { method: "patch", path: "/api/users/:id/role", summary: "Proxy update user role", tags: ["Users"], secured: true },
    { method: "patch", path: "/api/users/:id/status", summary: "Proxy update user status", tags: ["Users"], secured: true },
    { method: "post", path: "/api/users", summary: "Proxy create user", tags: ["Users"], secured: true },
    { method: "get", path: "/api/users/inspectors", summary: "Proxy list inspectors", tags: ["Users"], secured: true },
    { method: "get", path: "/api/extinguishers/meta", summary: "Proxy extinguisher metadata", tags: ["Extinguishers"], secured: true },
    { method: "get", path: "/api/extinguishers", summary: "Proxy list extinguishers", tags: ["Extinguishers"], secured: true },
    { method: "get", path: "/api/extinguishers/:id", summary: "Proxy extinguisher details", tags: ["Extinguishers"], secured: true },
    { method: "post", path: "/api/extinguishers", summary: "Proxy create extinguisher", tags: ["Extinguishers"], secured: true },
    { method: "patch", path: "/api/extinguishers/:id", summary: "Proxy update extinguisher", tags: ["Extinguishers"], secured: true },
    { method: "delete", path: "/api/extinguishers/:id", summary: "Proxy delete extinguisher", tags: ["Extinguishers"], secured: true },
    { method: "get", path: "/api/extinguishers/status/:status", summary: "Proxy extinguishers by status", tags: ["Extinguishers"], secured: true },
    { method: "get", path: "/api/extinguishers/location/:location", summary: "Proxy extinguishers by location", tags: ["Extinguishers"], secured: true },
    { method: "get", path: "/api/inspections/meta", summary: "Proxy inspection metadata", tags: ["Inspections"], secured: true },
    { method: "post", path: "/api/inspections", summary: "Proxy schedule inspection", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/inspections", summary: "Proxy list inspections", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/inspections/:id", summary: "Proxy inspection details", tags: ["Inspections"], secured: true },
    { method: "patch", path: "/api/inspections/:id", summary: "Proxy update inspection", tags: ["Inspections"], secured: true },
    { method: "delete", path: "/api/inspections/:id", summary: "Proxy delete inspection", tags: ["Inspections"], secured: true },
    { method: "patch", path: "/api/inspections/:id/complete", summary: "Proxy complete inspection", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/inspections/status/:status", summary: "Proxy inspections by status", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/inspections/overdue", summary: "Proxy overdue inspections", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/inspections/extinguisher/:extinguisherId", summary: "Proxy inspections by extinguisher", tags: ["Inspections"], secured: true },
    { method: "get", path: "/api/maintenance/meta", summary: "Proxy maintenance metadata", tags: ["Maintenance"], secured: true },
    { method: "post", path: "/api/maintenance", summary: "Proxy create maintenance log", tags: ["Maintenance"], secured: true },
    { method: "get", path: "/api/maintenance", summary: "Proxy list maintenance logs", tags: ["Maintenance"], secured: true },
    { method: "get", path: "/api/maintenance/:id", summary: "Proxy maintenance log details", tags: ["Maintenance"], secured: true },
    { method: "patch", path: "/api/maintenance/:id", summary: "Proxy update maintenance log", tags: ["Maintenance"], secured: true },
    { method: "delete", path: "/api/maintenance/:id", summary: "Proxy delete maintenance log", tags: ["Maintenance"], secured: true },
    { method: "get", path: "/api/maintenance/extinguisher/:extinguisherId", summary: "Proxy maintenance by extinguisher", tags: ["Maintenance"], secured: true },
    { method: "get", path: "/api/reports/meta", summary: "Proxy report metadata", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/dashboard", summary: "Proxy dashboard report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inventory", summary: "Proxy inventory report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inventory/daily", summary: "Proxy daily inventory report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inventory/monthly", summary: "Proxy monthly inventory report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inventory/yearly", summary: "Proxy yearly inventory report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inspections", summary: "Proxy inspection report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inspections/pending", summary: "Proxy pending inspections report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inspections/completed", summary: "Proxy completed inspections report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/inspections/overdue", summary: "Proxy overdue inspections report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/compliance", summary: "Proxy compliance report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/compliance/expired", summary: "Proxy expired compliance report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/compliance/upcoming-expirations", summary: "Proxy upcoming expirations report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/maintenance", summary: "Proxy maintenance report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/maintenance/history", summary: "Proxy maintenance history report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/maintenance/frequency", summary: "Proxy maintenance frequency report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/maintenance/recent", summary: "Proxy recent maintenance report", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/export/pdf", summary: "Proxy export reports as PDF", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/reports/export/csv", summary: "Proxy export reports as CSV", tags: ["Reports"], secured: true },
    { method: "get", path: "/api/notifications/meta", summary: "Proxy notification metadata", tags: ["Notifications"], secured: true },
    { method: "post", path: "/api/notifications/send", summary: "Proxy send notification", tags: ["Notifications"], secured: true },
    { method: "get", path: "/api/notifications", summary: "Proxy list notifications", tags: ["Notifications"], secured: true },
    { method: "get", path: "/api/notifications/:id", summary: "Proxy notification details", tags: ["Notifications"], secured: true },
    { method: "patch", path: "/api/notifications/:id/read", summary: "Proxy mark notification as read", tags: ["Notifications"], secured: true },
    { method: "patch", path: "/api/notifications/:id", summary: "Proxy update notification", tags: ["Notifications"], secured: true },
    { method: "delete", path: "/api/notifications/:id", summary: "Proxy delete notification", tags: ["Notifications"], secured: true },
    { method: "get", path: "/api/notifications/type/:type", summary: "Proxy notifications by type", tags: ["Notifications"], secured: true },
    { method: "get", path: "/api/notifications/user/:userId", summary: "Proxy notifications by user", tags: ["Notifications"], secured: true }
  ]
});
